name: simple_jwt_manager
description: "This is a package that supports authentication using the ROPC defined in RFC 6749."
version: 0.0.30
repository: https://github.com/MasahideMori-SimpleAppli/simple_jwt_manager

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0